### ISSUE TITLE
apollo生态兼容

### ISSUE THREAD

**Issue by tianxiaoliang** [apache/servicecomb-kie#154]
背景：
如今，apollo已经非常的流行，大量的遗留系统都使用了这套系统。

需求描述：

我们的label有很大的灵活性，尝试找到一个兼容apollo API的方案，来无缝支持apollo生态的client和agent，可能只是有限支持，要看下

**Comment by GuoYL123** [comment]
kie服务端兼容apollo难以直接直接对接apollo原生客户端，客户端可能无法避免改造成本，转为客户端兼容
