### ISSUE TITLE
how can i generate doc/api.yaml when i add some new api?

### ISSUE THREAD

**Issue by nisainan** [apache/servicecomb-kie#239]
i add one new api for listing all projects, but i dont know how to generate api.yaml,pls give some help ,thx.

**Comment by tianxiaoliang** [comment]
after you write this code https://github.com/apache/servicecomb-kie/blob/e04d21713ac61ce69a224445d056f9d497ef2ecf/server/resource/v1/kv_resource.go#L360

the program will automaticaly generate doc in file path
refer to https://go-chassis.readthedocs.io/en/latest/user-guides/contract.html
