### ISSUE TITLE
全新环境，按文档部署失败

### ISSUE THREAD

**Issue by shaohean** [apache/servicecomb-kie#274]
docker-compose启动时，

mongo-express服务有如下提示：

(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

kie服务有如下提示：

{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:181","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:186","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:181","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:186","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:181","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:186","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:181","msg":"Parse services from config failed: input must be an ptr"}
{"level":"ERROR","timestamp":"2022-12-21 07:43:50.350 +00:00","file":"servicecomb/transfer.go:186","msg":"Parse services from config failed: input must be an ptr"}

**Comment by tianxiaoliang** [comment]
请提供下复复现步骤

**Comment by shaohean** [comment]
使用的是这个文档  https://kie.readthedocs.io/en/latest/getstarted/install.html#run-locally-with-docker-compose
步骤如下:

git clone git@github.com:apache/servicecomb-kie.git
cd servicecomb-kie/deployments/docker
docker-compose up

注,运行环境:
操作系统centos7.7.1908(最小化安装)
git 版本1.8.3.1
docker版本为:20.10.21
docker-compose版本为:v2.14.2
