### ISSUE TITLE
How to run kie without docker

### ISSUE THREAD

**Issue by ChinX** [apache/servicecomb-kie#31]

**Comment by liangyuanpeng** [comment]
It looks like you have to have a docker

I tried build but failed because docker was not enabled

**Comment by liangyuanpeng** [comment]
starting docker and still build failed

```
Successfully built 9dba29f32eb7
Successfully tagged servicecomb/kie:0.0.1
building arm64
# github.com/apache/servicecomb-kie/cmd/kieserver
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/fx/sq4twr6d2ll6df7046kpfmnh0000gn/T/go-link-083027331/go.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/fx/sq4twr6d2ll6df7046kpfmnh0000gn/T/go-link-083027331/go.o
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

packaging arm64 tar.gz...
```

**Comment by alec-z** [comment]
already add a new file build_native_server.sh in build directory. Which can build kie without docker.

**Comment by alec-z** [comment]
If you want run kie natively without docker in mac os. Update code to the newest.
1.run build/build_native_server.sh.
2.run mongoDB first
3.unzip release/kie/apache-servicecomb-kie--darwin-amd64.tar.gz, change conf/kie-conf.yaml, and run kie。

**Comment by WillemJiang** [comment]
@alec-z Could you send a PR to update the readme file for it?

**Comment by alec-z** [comment]
Already add a new PR for readme in docs .

**Comment by WillemJiang** [comment]
@alec-z  Can you add the link for PR and close this issue if it is resolved?

**Comment by alec-z** [comment]
see https://github.com/apache/servicecomb-kie/pull/38
