### ISSUE TITLE
The API paths in swagger are inconsistent with the actual paths when I start the service with docker

### ISSUE THREAD

**Issue by zaneChou1** [apache/servicecomb-kie#48]
when I start the service with docker, return API path as follows, and access success.
```
"Add route path: [/v1/kv/{key}] Method: [PUT] Func: [Put]. 
"Add route path: [/v1/kv/{key}] Method: [GET] Func: [GetByKey].
"Add route path: [/v1/kv] Method: [GET] Func: [SearchByLabels]. 
"Add route path: [/v1/kv/{kvID}] Method: [DELETE] Func: [Delete].
```
but in the swagger, the API path as follows, and access failed.
```
"Add route path: [/v1/{project}/kie/kv/{key}] Method: [PUT] Func: [Put]. 
"Add route path: [/v1/{project}/kie/kv/{key}] Method: [GET] Func: [GetByKey].
"Add route path: [/v1/{project}/kie/kv] Method: [GET] Func: [SearchByLabels]. 
"Add route path: [/v1/{project}/kie/kv/{kvID}] Method: [DELETE] Func: [Delete].
```
I'm a bit confused. I think the two API paths should be the same, and what they should be.

**Comment by alec-z** [comment]
The docker image servicecomb/kie:latest in hub.docker.com is outdated. Please push the really latest kie to hub.docker.com then the issue will gone.

**Comment by tianxiaoliang** [comment]
updated docker 

https://cloud.docker.com/u/servicecomb/repository/docker/servicecomb/kie/general
