### ISSUE TITLE
about api : /v1/{project}/kie/summary

### ISSUE THREAD

**Issue by GuoYL123** [apache/servicecomb-kie#62]
I noticed that in api _/v1/{project}/kie/summary_  ，**q** was used as the query.
But in api _/v1/{project}/kie/kv/{key}_ and _/v1/{project}/kie/kv_ ,the query is **label**.
**q** and **label** seem like the same meaning, should we unit them ?

**Comment by tianxiaoliang** [comment]
no, they got different format, take a look at it

**Comment by GuoYL123** [comment]
Another problem : KVDoc.value_type  and  KVBody.valueType  is the same name but different style

**Comment by tianxiaoliang** [comment]
该接口先删除，不成熟
