### ISSUE TITLE
label数据一致性问题

### ISSUE THREAD

**Issue by tianxiaoliang** [apache/servicecomb-kie#68]
当前实现，如果并发创建label完全一致的两条key的时候（且label之前从未存在过），会导致重复label数据。

一种方法是可以将map进行format按序排列生成一个unique id，避免重复label记录

也可以想想有什么更好的方法

**Comment by GuoYL123** [comment]
label ID是 domain + project 唯一还是 全局唯一？

**Comment by tianxiaoliang** [comment]
label id 本身是个unique id，alias+domainid+project还是需要一个uniqueid 保证约束

**Comment by GuoYL123** [comment]
label id全局唯一
alias+domainid+project全局唯一
这样？

**Comment by tianxiaoliang** [comment]
对

GuoYL <notifications@github.com> 于2020年1月14日周二 下午5:31写道：

**Comment by tianxiaoliang** [comment]
已解决
